ENV['RCT_NEW_ARCH_ENABLED'] = '0'
ENV['USE_FRAMEWORKS'] = 'static'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

source 'https://cdn.cocoapods.org'
source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/bidon-io/CocoaPods_Specs.git'

# Appodeal SDK 3.10.0.0
def appodeal
  pod 'Appodeal', '3.10.0'
  # pod 'APDAdjustAdapter', '3.10.0.0'
  # pod 'APDAmazonAdapter', '3.10.0.0'
  # pod 'APDAppLovinAdapter', '3.10.0.0'
  # pod 'APDAppLovinMAXAdapter', '3.10.0.0'
  # pod 'APDAppsFlyerAdapter', '3.10.0.0'
  # pod 'APDBidMachineAdapter', '3.10.0.0'
  # pod 'APDBidonAdapter', '3.10.0.0'
  # pod 'APDBigoAdsAdapter', '3.10.0.0'
  # pod 'APDDTExchangeAdapter', '3.10.0.0'
  # pod 'APDFacebookAdapter', '3.10.0.0'
  # pod 'APDFirebaseAdapter', '3.10.0.0'
  pod 'APDGoogleAdMobAdapter', '3.10.0.0'
  # pod 'APDIABAdapter', '3.10.0.0'
  # pod 'APDInMobiAdapter', '3.10.0.0'
  # pod 'APDIronSourceAdapter', '3.10.0.0'
  # pod 'APDLevelPlayAdapter', '3.10.0.0'
  # pod 'APDMetaAudienceNetworkAdapter', '3.10.0.0'
  # pod 'APDMintegralAdapter', '3.10.0.0'
  # pod 'APDMyTargetAdapter', '3.10.0.0'
  # pod 'APDPangleAdapter', '3.10.0.0'
  # pod 'APDSmaatoAdapter', '3.10.0.0'
  # pod 'APDSentryAdapter', '3.10.0.0'
  # pod 'APDUnityAdapter', '3.10.0.0'
  # pod 'APDVungleAdapter', '3.10.0.0'
  # pod 'APDYandexAdapter', '3.10.0.0'
  # pod 'AppLovinMediationAmazonAdMarketplaceAdapter', '5.3.0.0'
  # pod 'AppLovinMediationBidMachineAdapter', '3.4.0.0.0'
  # pod 'AppLovinMediationBidonAdapter', '0.11.0.0'
  # pod 'AppLovinMediationBigoAdsAdapter', '4.9.0.0'
  # pod 'AppLovinMediationByteDanceAdapter', '7.4.1.1.0'
  # pod 'AppLovinMediationChartboostAdapter', '9.9.2.1'
  # pod 'AppLovinMediationFacebookAdapter', '6.20.1.0'
  # pod 'AppLovinMediationFyberAdapter', '8.3.8.0'
  # pod 'AppLovinMediationGoogleAdManagerAdapter', '12.8.0.0'
  # pod 'AppLovinMediationGoogleAdapter', '12.8.0.0'
  # pod 'AppLovinMediationInMobiAdapter', '10.8.6.0'
  # pod 'AppLovinMediationIronSourceAdapter', '8.10.0.0.0'
  # pod 'AppLovinMediationMintegralAdapter', '7.7.9.0.0'
  # pod 'AppLovinMediationMobileFuseAdapter', '1.9.2.1'
  # pod 'AppLovinMediationMolocoAdapter', '3.12.0.0'
  # pod 'AppLovinMediationMyTargetAdapter', '5.33.0.0'
  # pod 'AppLovinMediationOguryPresageAdapter', '5.0.2.0'
  # pod 'AppLovinMediationPubMaticAdapter', '4.8.0.0'
  # pod 'AppLovinMediationSmaatoAdapter', '22.9.3.1'
  # pod 'AppLovinMediationUnityAdsAdapter', '4.16.0.0'
  # pod 'AppLovinMediationVerveAdapter', '3.6.0.0'
  # pod 'AppLovinMediationVungleAdapter', '7.5.2.0'
  # pod 'AppLovinMediationYandexAdapter', '7.14.1.0'
  # pod 'BidMachineAmazonAdapter', '3.4.0.0'
  # pod 'BidMachineIronSourceCustomAdapter', '3.4.0.0'
  # pod 'BidMachineMetaAudienceAdapter', '3.4.0.0'
  # pod 'BidMachineMintegralAdapter', '3.4.0.0'
  # pod 'BidMachineMyTargetAdapter', '3.4.0.0'
  # pod 'BidMachinePangleAdapter', '3.4.0.0'
  # pod 'BidMachineVungleAdapter', '3.4.0.0'
  # pod 'BidonAdapterAmazon', '0.11.0.0'
  # pod 'BidonAdapterBidMachine', '0.11.0.0'
  # pod 'BidonAdapterBigoAds', '0.11.0.0'
  # pod 'BidonAdapterChartboost', '0.11.0.0'
  # pod 'BidonAdapterDTExchange', '0.11.0.0'
  # pod 'BidonAdapterInMobi', '0.11.0.0'
  # pod 'BidonAdapterIronSource', '0.11.0.0'
  # pod 'BidonAdapterMetaAudienceNetwork', '0.11.0.0'
  # pod 'BidonAdapterMintegral', '0.11.0.0'
  # pod 'BidonAdapterMobileFuse', '0.11.0.0'
  # pod 'BidonAdapterMoloco', '0.11.0.0'
  # pod 'BidonAdapterMyTarget', '0.11.0.0'
  # pod 'BidonAdapterUnityAds', '0.11.0.0'
  # pod 'BidonAdapterVungle', '0.11.0.0'
  # pod 'BidonAdapterYandex', '0.11.0.0'
  # pod 'ISBidonCustomAdapter', '0.11.0.0'
  # pod 'IronSourceAPSAdapter', '4.3.21.0'
  # pod 'IronSourceAdMobAdapter', '4.3.69.0'
  # pod 'IronSourceAppLovinAdapter', '4.3.56.0'
  # pod 'IronSourceBidMachineAdapter', '4.3.20.0'
  # pod 'IronSourceBigoAdapter', '4.3.8.0'
  # pod 'IronSourceFacebookAdapter', '4.3.51.0'
  # pod 'IronSourceFyberAdapter', '4.3.44.0'
  # pod 'IronSourceInMobiAdapter', '4.3.30.0'
  # pod 'IronSourceMintegralAdapter', '4.3.37.0'
  # pod 'IronSourceMobileFuseAdapter', '4.3.8.1'
  # pod 'IronSourceMolocoAdapter', '4.3.22.0'
  # pod 'IronSourceMyTargetAdapter', '4.3.6.0'
  # pod 'IronSourceOguryAdapter', '4.3.3.1'
  # pod 'IronSourcePangleAdapter', '4.3.51.0'
  # pod 'IronSourceSmaatoAdapter', '4.3.17.1'
  # pod 'IronSourceUnityAdsAdapter', '4.3.54.0'
  # pod 'IronSourceVerveAdapter', '4.3.6.1'
  # pod 'IronSourceVungleAdapter', '4.3.46.0'
  # pod 'IronSourceYandexAdapter', '4.3.21.0'
end

target 'AppodealExample' do
  config = use_native_modules!
  use_modular_headers!
  appodeal

  # 🔧 Manually override reactNativePath to point to the root node_modules
  # bypassing the example/node_modules symlink to fix path resolution issues
  # with USE_FRAMEWORKS=static in a monorepo.
  # Relative to example/ios/:
  config[:reactNativePath] = '../../node_modules/react-native'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )
    
    # ⚡️ Optimize build time: Only build active architecture for Debug
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        if build_config.name == 'Debug'
          build_config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        end
      end
    end


    # 🔧 Fix "Multiple commands produce" errors for duplicate headers
    # React-Fabric has CopyFiles phases that duplicate headers already
    # provided by React-FabricComponents (scrollview) and
    # React-rendererconsistency (consistency). Remove the duplicate
    # CopyFiles phases from React-Fabric.
    other_targets = ['React-FabricComponents', 'React-rendererconsistency']
    other_dst_paths = Set.new
    other_targets.each do |name|
      t = installer.pods_project.targets.find { |t| t.name == name }
      next unless t
      t.build_phases.each do |phase|
        next unless phase.is_a?(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase)
        other_dst_paths.add(phase.dst_path) if phase.dst_path
      end
    end

    fabric_target = installer.pods_project.targets.find { |t| t.name == 'React-Fabric' }
    if fabric_target && !other_dst_paths.empty?
      # Remove duplicate CopyFiles phases from React-Fabric
      fabric_target.build_phases.delete_if do |phase|
        phase.is_a?(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase) &&
          phase.dst_path && other_dst_paths.include?(phase.dst_path)
      end

      # Also remove duplicate header entries from React-Fabric's Headers phase
      other_header_names = Set.new
      other_targets.each do |name|
        t = installer.pods_project.targets.find { |t| t.name == name }
        next unless t
        t.build_phases.each do |phase|
          next unless phase.is_a?(Xcodeproj::Project::Object::PBXHeadersBuildPhase)
          phase.files.each do |file|
            other_header_names.add(file.display_name) rescue nil
          end
        end
      end

      fabric_target.build_phases.each do |phase|
        next unless phase.is_a?(Xcodeproj::Project::Object::PBXHeadersBuildPhase)
        phase.files.delete_if do |file|
          name = file.display_name rescue nil
          name && other_header_names.include?(name)
        end
      end
    end
  end
end
